In [1]:
#read datafolder from Google Drive
from google.colab import drive
drive.mount('/content/drive')
data_folder = '/content/drive/My Drive/reuters21578/'


sgml_number_of_files = 21
sgml_file_name_template = 'reut2-NNN.sgm'

# Category files
category_files = {
    'to_': ('Topics', 'all-topics-strings.lc.txt'),
    'pl_': ('Places', 'all-places-strings.lc.txt'),
    'pe_': ('People', 'all-people-strings.lc.txt'),
    'or_': ('Organizations', 'all-orgs-strings.lc.txt'),
    'ex_': ('Exchanges', 'all-exchanges-strings.lc.txt')
}

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
import pandas as pd
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

In [0]:
# Create category dataframe

# Read all categories
category_data = []
category_dictionary={'Topics':[],'Places':[],'People':[],'Organizations':[],'Exchanges':[]}
for category_prefix in category_files.keys():
    with open(data_folder + category_files[category_prefix][1], 'r') as file:
        for category in file.readlines():
            category_data.append([category_prefix + category.strip().lower(), 
                                  category_files[category_prefix][0]])

# Create category dataframe
for i in category_data:
#     print(i[1])
    category_dictionary[i[1]].append(i[0].split('_')[1])
news_categories = pd.DataFrame(data=category_data)

# print "category_data: ", category_data
#(news_categories.values).tolist()

In [4]:
import re
import xml.sax.saxutils as saxutils
from bs4 import BeautifulSoup
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
import nltk
nltk.download('stopwords')

Using TensorFlow backend.


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [0]:
lemmatizer = WordNetLemmatizer()

REPLACE_BY_SPACE_RE = re.compile('[/(){}\[\]\|@,;\\n]')
BAD_SYMBOLS_RE = re.compile('[^0-9a-z #+_]')
STOPWORDS = set(stopwords.words('english'))

def cleanUpSentence(r):#, stop_words = None#
    r = r.lower().replace("<br />", " ")
    r = REPLACE_BY_SPACE_RE.sub(' ', r)
    r = BAD_SYMBOLS_RE.sub('', r)

    r = ' '.join(word for word in r.split() if word not in STOPWORDS)

    words = word_tokenize(r)

    for w in words:
        w = lemmatizer.lemmatize(w)

    return r

In [0]:
# Parse SGML files
def strip_tags(text):
    return re.sub('<[^<]+?>', '', text).strip()

def unescape(text):
    return saxutils.unescape(text)
  
def makeDict(filename, document_X):
  with open(filename, 'rb') as file:

    content = BeautifulSoup(file.read().lower(),'html.parser')

    for newsline in content('reuters'):
      document_categories = []

      document_id = newsline['newid']
      document_body = strip_tags(str(newsline('text')[0].body)).replace('reuter\n&#3;', '')
      if document_body == 'None':
        continue

      doc_categories = strip_tags(str(newsline('topics')[0].body))
      doc_categories = unescape(doc_categories)

      document_body = unescape(document_body)

      document_X[document_id] = document_body

def readFiles(test_data = False):
  document_X = {}
  
  if test_data == True:
    file_name = sgml_file_name_template.replace('NNN', '021')
    filename = data_folder + file_name
    makeDict(filename, document_X)
  else:
    for i in range(sgml_number_of_files):
      if i < 10:
        seq = '00' + str(i)
      else:
        seq = '0' + str(i)

      file_name = sgml_file_name_template.replace('NNN', seq)
      print('Reading file: %s' % file_name)
      filename = data_folder + file_name
      makeDict(filename, document_X)
  return document_X



In [7]:
document_X= readFiles()

Reading file: reut2-000.sgm
Reading file: reut2-001.sgm
Reading file: reut2-002.sgm
Reading file: reut2-003.sgm
Reading file: reut2-004.sgm
Reading file: reut2-005.sgm
Reading file: reut2-006.sgm
Reading file: reut2-007.sgm
Reading file: reut2-008.sgm
Reading file: reut2-009.sgm
Reading file: reut2-010.sgm
Reading file: reut2-011.sgm
Reading file: reut2-012.sgm
Reading file: reut2-013.sgm
Reading file: reut2-014.sgm
Reading file: reut2-015.sgm
Reading file: reut2-016.sgm
Reading file: reut2-017.sgm
Reading file: reut2-018.sgm
Reading file: reut2-019.sgm
Reading file: reut2-020.sgm


In [8]:
# data preprocessing
import numpy as np

nltk.download('punkt')
nltk.download('wordnet')

def create_x_matrix(document_X):
    totalX = []
    for i, doc in document_X.items():
        totalX.append(cleanUpSentence(doc))
    max_vocab_size = 200
    input_tokenizer = Tokenizer(200)
    input_tokenizer.fit_on_texts(totalX)
    encoded_docs = input_tokenizer.texts_to_matrix(totalX, mode='count')
    return totalX,encoded_docs

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.


In [0]:
totalX,encoded_docs=create_x_matrix(document_X)

In [0]:
#Create one-hot encode
def makeOneHotEncoding(totalX):
  words_in_body={}

  for i in range(len(totalX)):
      words=totalX[i].split(' ')
      words_in_body[i]=words    

  one_hot_label=[]
  for key,v in words_in_body.items():
      dict_temp={'Topics':0,'Places':0,'People':0,'Exchanges':0,'Organizations':0}
      for i in v:
          if i in category_dictionary['Topics']:
              dict_temp['Topics']+=1
          if i in category_dictionary['Places']:
              dict_temp['Places']+=1
          if i in category_dictionary['People']:
              dict_temp['People']+=1
          if i in category_dictionary['Exchanges']:
              dict_temp['Exchanges']+=1
          if i in category_dictionary['Organizations']:
              dict_temp['Organizations']+=1

      one_hot_label.append(dict_temp)


  one_hot_label_list = []
  for i in one_hot_label:

      one_hot_label_list.append(list(i.values()))
  return one_hot_label_list

In [0]:
one_hot_label_list = makeOneHotEncoding(totalX)

In [32]:
from keras.models import Sequential
from keras.layers import Dense,Flatten, Dropout,Embedding
nn = Sequential()
max_vocab_size = 200
nn.add(Embedding(200, 20, input_length=max_vocab_size))
nn.add(Dense(10, activation="relu", input_shape=(max_vocab_size,)))
nn.add(Dropout(0.15))
nn.add(Flatten())
nn.add(Dense(5,activation="sigmoid"))
nn.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
nn.fit(np.array(encoded_docs), np.array(one_hot_label_list), batch_size=16, epochs=5,
          verbose=1, validation_split=0.2)

Train on 14866 samples, validate on 3717 samples
Epoch 1/5
14866/14866 [==============================] - 4s 255us/step - loss: -2.0585 - acc: 0.6430 - val_loss: -2.7405 - val_acc: 0.6498
Epoch 2/5
14866/14866 [==============================] - 3s 225us/step - loss: -2.8458 - acc: 0.6805 - val_loss: -2.9162 - val_acc: 0.6810
Epoch 3/5
14866/14866 [==============================] - 3s 232us/step - loss: -2.9841 - acc: 0.6919 - val_loss: -2.9162 - val_acc: 0.6905
Epoch 4/5
14866/14866 [==============================] - 3s 231us/step - loss: -3.0190 - acc: 0.6957 - val_loss: -2.9287 - val_acc: 0.6970
Epoch 5/5
14866/14866 [==============================] - 3s 231us/step - loss: -3.9259 - acc: 0.7394 - val_loss: -4.2117 - val_acc: 0.7531


In [33]:
test_document_X = readFiles(test_data=True)
print(len(test_document_X))

460


In [35]:
test_total_X,test_encoded_X= create_x_matrix(test_document_X)
ground_truth_list = makeOneHotEncoding(test_total_X)
y = nn.predict(test_encoded_X)
print (y)

[[1.0000000e+00 1.0000000e+00 9.8665559e-01 1.2957960e-02 5.9604645e-08]
 [9.9999988e-01 1.0000000e+00 1.8958408e-01 2.4525970e-02 9.9791110e-01]
 [9.2870045e-01 4.8561668e-01 2.6583672e-05 9.9993384e-01 5.0514936e-05]
 ...
 [6.2159508e-01 8.9557052e-01 3.1722188e-03 2.4079382e-03 1.7920136e-04]
 [9.9999404e-01 1.0504186e-02 1.0000000e+00 5.6911498e-02 8.3446503e-07]
 [1.0000000e+00 1.0000000e+00 9.9998796e-01 2.0865923e-01 4.5303605e-04]]


In [0]:
def permissible(x, y):
  if (abs(x-y)) < 2:
    return True
  else:
    return False

def accuracy(predicted,actual):
    tp=0
    fp = 0
    tp_list = []
    length = len(actual)
    print("length: ",length)
    for one_doc_idx in range(length):
        if permissible(predicted[one_doc_idx][0],actual[one_doc_idx][0]) and permissible(predicted[one_doc_idx][1],actual[one_doc_idx][1])\
          and permissible(predicted[one_doc_idx][2],actual[one_doc_idx][2]) and permissible(predicted[one_doc_idx][3],actual[one_doc_idx][3]):
            tp+=1
            x = tp
        else:
          fp = 0
          x = fp
        tp_list.append(x)
    return tp/float(length), tp_list

In [37]:
def getRankedOutput2(predicted_y):
    all_sorted_x = []
    for i in predicted_y:
        dict_temp={'Topics':i[0],'Places':i[1],'Peoples':i[2],'Exchanges':i[3],'Organizations':i[4]}
        sorted_x = sorted(dict_temp.items(), key=lambda kv: kv[1], reverse=True) 
        all_sorted_x.append(sorted_x)
    return all_sorted_x
   
acc, tpl = accuracy(y.tolist(), ground_truth_list)
print ("%f"%acc)
predicted_ranked_output = getRankedOutput2(y)
actual_ranked_output=getRankedOutput2(np.array(ground_truth_list))

length:  460
0.834783


In [38]:
my_df  = pd.DataFrame(columns = ['body', 'predicted ranking', 'actual ranking', '_'])
my_df['body'] = test_total_X
my_df['predicted ranking'] = predicted_ranked_output 
my_df['actual ranking'] = actual_ranked_output
my_df['_'] = tpl
my_df = my_df.sort_values(by='_', ascending=False).reset_index(drop=True)
my_df[['body', 'predicted ranking', 'actual ranking']]

body  \
0    prospect dominant alliance socialists environm...   
1    japan indiapakistangulf japan shipping confere...   
2    announcement alliant computer systems inc alnt...   
3    chase corp ltd chcawe said make offer fullypai...   
4    thai rice exports rose 72 987 tonnes week ende...   
5    orders nonfuel imports placed august rose seas...   
6    new zealand imposed sanctions fiji response co...   
7    iranian president ali khamenei said doubted us...   
8    philippines trade deficit widened 542 mln dlrs...   
9    nippon shinpan co ltd nshtt agreed mastercard ...   
10   continental airlines inc said frontier airline...   
11   french finance minister edouard balladur issue...   
12   third quarter ended august 31 group shr 3492 y...   
13   nine months ended august 31 group shr 11866 ye...   
14   norwegian computer company norsk data norkol s...   
15   lebanons bankers association said extended sus...   
16   equiticorp holdings ltd equwwe owns received a...   
17   british printing communication corporation plc...   
18   philippine 1987 inflation rate rise 48 pct 074...   
19   swedish export credit corp sek raising 300 mln...   
20   lloyds shipping intelligence service said brit...   
21   finnish state launched two bonds totalling one...   
22   cyprus vessel fearless 31 841 tonnes dw fire g...   
23   raffles city pte ltd said signed 10 year note ...   
24   west german finance ministry declined comment ...   
25   norways current account showed 99 billion crow...   
26   main road kampala kenya border ugandas importa...   
27   king baudouin expected accept resignation belg...   
28   hyundai auto canada inc unit south koreas hyun...   
29   french finance minister edouard balladur issue...   
..                                                 ...   
430  us attack iranian oil platform gulf monday app...   
431  canada development corp said polysar ltd unit ...   
432  arizona silver corp said diamond drilling burr...   
433  phelps dodge corp said net earnings nearly tri...   
434  us defense department spokesman said informati...   
435  salomon brothers inc withdrawing market maker ...   
436  reserve bank india said tightening credit poli...   
437  thai traders plan establish company regulate m...   
438  us television networks said monday us forces l...   
439  thriving market luxembourg franc bond issues t...   
440  shr 52 cts vs 43 cts net 177 mln vs 142 mln sa...   
441  saudi arabia likely remain key supplier liquef...   
442  unidentified jets attacked three iranian oil r...   
443  south koreas national news agency yonhap said ...   
444  us warships attacked destroyed iranian oil pla...   
445  oper shr loss 82 cts vs profit 12 cts oper net...   
446  soviet planning chief nikolai talyzin told sup...   
447  todays sharp selloff swiss stocks matching fal...   
448  nui corp said studying feasibility spinning no...   
449  turkeys current account deficit widened july 6...   
450  australian minister trade negotiations michael...   
451  security pacific corp spc said growth thirdqua...   
452  calfed inc said strong loan volume higher net ...   
453  us energy secretary john herrington arrived ra...   
454  official soviet news agency tass denounced us ...   
455  shr primary 68 cts vs 34 cts shr diluted 65 ct...   
456  financial corp america reporting third quarter...   
457  recent sharp rise us interest rates sparked tu...   
458  west german government sources said bonn remai...   
459  american stock exchange said introduced option...   

                                     predicted ranking  \
0    [(Peoples, 1.0), (Topics, 0.99999404), (Exchan...   
1    [(Topics, 0.9994123), (Places, 0.9676466), (Pe...   
2    [(Topics, 1.0), (Places, 1.0), (Peoples, 1.0),...   
3    [(Topics, 1.0), (Peoples, 0.99321073), (Places...   
4    [(Topics, 0.99773145), (Places, 0.008059651), ...   
5    [(Topics, 0.9999969), (Places, 0.36535674), (E...   
6    [(Topics, 1.0), (Places, 0.99999404), (Peo